import "./globals.css";
import "./font.css";
import { Metadata } from "next";
import { AuthProvider } from "@/contexts/authContexts";
import NextNProgress from "nextjs-toploader";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "확신의 1등급! 주혜연T",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextNProgress color={"#1d4ed8"} height={5} shadow={false} />
          <AuthProvider>
            {children}
          </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
