import "./globals.css";
import "./font.css";
import { Metadata } from "next";
import { AuthProvider } from "@/contexts/authContexts";
import NextNProgress from "nextjs-toploader";

export const metadata: Metadata = {
  title: "확신의 1등급! 주혜연T",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* 폰트 프리로딩 */}
        <link
          rel="preload"
          href="/fonts/MaruBuri/MaruBuri-Light.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/MaruBuri/MaruBuri-SemiBold.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/MaruBuri/MaruBuri-Bold.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        {/* LCP 이미지 프리로딩 */}
        <link
          rel="preload"
          href="/homeCopy/jooMain.png"
          as="image"
          type="image/png"
        />
      </head>
      <body>
        <NextNProgress color={"#1d4ed8"} height={5} shadow={false} />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
