import "./globals.css";
import "./font.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "임호열 영어학원",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
